/*
 * Selling Partner API for Direct Fulfillment Transaction Status
 *
 * The Selling Partner API for Direct Fulfillment Transaction Status provides programmatic access to a direct fulfillment vendor's transaction status.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorDirectFulfillmentTransactions
{
    /// <summary>
    /// The payload for the getTransactionStatus operation.
    /// </summary>
    [DataContract]
    public partial class TransactionStatus :  IEquatable<TransactionStatus>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionStatus" /> class.
        /// </summary>
        [JsonConstructor]
        public TransactionStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionStatus" /> class.
        /// </summary>
        /// <param name="transactionStatus">transactionStatus.</param>
        public TransactionStatus(Transaction transactionStatus = default(Transaction))
        {
            this._TransactionStatus = transactionStatus;
        }

        /// <summary>
        /// Gets or Sets TransactionStatus
        /// </summary>
        [DataMember(Name="transactionStatus", EmitDefaultValue=false)]
        public Transaction _TransactionStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionStatus {\n");
            sb.Append("  TransactionStatus: ").Append(_TransactionStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionStatus);
        }

        public bool Equals(TransactionStatus input)
        {
            if (input == null)
                return false;

            return
                (
                    this._TransactionStatus == input._TransactionStatus ||
                    (this._TransactionStatus != null &&
                    this._TransactionStatus.Equals(input._TransactionStatus))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._TransactionStatus != null)
                    hashCode = hashCode * 59 + this._TransactionStatus.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}