/*
 * Selling Partner API for Direct Fulfillment Payments
 *
 * The Selling Partner API for Direct Fulfillment Payments provides programmatic access to a direct fulfillment vendor's invoice data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorDirectFulfillmentPayments
{
    /// <summary>
    /// Response containing the transaction ID.
    /// </summary>
    [DataContract]
    public partial class TransactionReference :  IEquatable<TransactionReference>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionReference" /> class.
        /// </summary>
        [JsonConstructor]
        public TransactionReference() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionReference" /> class.
        /// </summary>
        /// <param name="transactionId">GUID to identify this transaction. This value can be used with the Transaction Status API to return the status of this transaction.</param>
        public TransactionReference(string transactionId = default(string))
        {
            this.TransactionId = transactionId;
        }
        
        /// <summary>
        /// GUID to identify this transaction. This value can be used with the Transaction Status API to return the status of this transaction.
        /// </summary>
        /// <value>GUID to identify this transaction. This value can be used with the Transaction Status API to return the status of this transaction.</value>
        [DataMember(Name="transactionId", EmitDefaultValue=false)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionReference {\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionReference);
        }

        public bool Equals(TransactionReference input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TransactionId == input.TransactionId ||
                    (this.TransactionId != null &&
                    this.TransactionId.Equals(input.TransactionId))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TransactionId != null)
                    hashCode = hashCode * 59 + this.TransactionId.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}