/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to vendor shipment data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorShipments
{
    /// <summary>
    /// Carton reference details.
    /// </summary>
    [DataContract]
    public partial class CartonReferenceDetails :  IEquatable<CartonReferenceDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartonReferenceDetails" /> class.
        /// </summary>
        [JsonConstructor]
        public CartonReferenceDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CartonReferenceDetails" /> class.
        /// </summary>
        /// <param name="cartonCount">Pallet level carton count is mandatory for single item pallet and optional for mixed item pallet.</param>
        /// <param name="cartonReferenceNumbers">Array of reference numbers for the carton that are part of this pallet/shipment. Please provide the cartonSequenceNumber from the 'cartons' segment to refer to that carton's details here. (required)</param>
        public CartonReferenceDetails(int? cartonCount = default(int?), List<string> cartonReferenceNumbers = default(List<string>))
        {
            this.CartonCount = cartonCount;
            // to ensure "cartonReferenceNumbers" is required (not null)
            if (cartonReferenceNumbers == null)
            {
                throw new InvalidDataException("cartonReferenceNumbers is a required property for CartonReferenceDetails and cannot be null");
            }
            else
            {
                this.CartonReferenceNumbers = cartonReferenceNumbers;
            }
        }
        
        /// <summary>
        /// Pallet level carton count is mandatory for single item pallet and optional for mixed item pallet.
        /// </summary>
        /// <value>Pallet level carton count is mandatory for single item pallet and optional for mixed item pallet.</value>
        [DataMember(Name="cartonCount", EmitDefaultValue=false)]
        public int? CartonCount { get; set; }

        /// <summary>
        /// Array of reference numbers for the carton that are part of this pallet/shipment. Please provide the cartonSequenceNumber from the 'cartons' segment to refer to that carton's details here.
        /// </summary>
        /// <value>Array of reference numbers for the carton that are part of this pallet/shipment. Please provide the cartonSequenceNumber from the 'cartons' segment to refer to that carton's details here.</value>
        [DataMember(Name="cartonReferenceNumbers", EmitDefaultValue=false)]
        public List<string> CartonReferenceNumbers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CartonReferenceDetails {\n");
            sb.Append("  CartonCount: ").Append(CartonCount).Append("\n");
            sb.Append("  CartonReferenceNumbers: ").Append(CartonReferenceNumbers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as CartonReferenceDetails);
        }

        public bool Equals(CartonReferenceDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CartonCount == input.CartonCount ||
                    (this.CartonCount != null &&
                    this.CartonCount.Equals(input.CartonCount))
                ) && 
                (
                    this.CartonReferenceNumbers == input.CartonReferenceNumbers ||
                    (this.CartonReferenceNumbers != null &&
                    this.CartonReferenceNumbers.Equals(input.CartonReferenceNumbers))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CartonCount != null)
                    hashCode = hashCode * 59 + this.CartonCount.GetHashCode();
                if (this.CartonReferenceNumbers != null)
                    hashCode = hashCode * 59 + this.CartonReferenceNumbers.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}