/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to vendor shipment data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorShipments
{
    /// <summary>
    /// Container sequence numbers that are involved in this shipment.
    /// </summary>
    [DataContract]
    public partial class ContainerSequenceNumbers :  IEquatable<ContainerSequenceNumbers>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContainerSequenceNumbers" /> class.
        /// </summary>
        [JsonConstructor]
        public ContainerSequenceNumbers() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContainerSequenceNumbers" /> class.
        /// </summary>
        /// <param name="containerSequenceNumber">A list of containers shipped</param>
        public ContainerSequenceNumbers(string containerSequenceNumber = default(string))
        {
            this.ContainerSequenceNumber = containerSequenceNumber;
        }
        
        /// <summary>
        /// A list of containers shipped
        /// </summary>
        /// <value>A list of containers shipped</value>
        [DataMember(Name="containerSequenceNumber", EmitDefaultValue=false)]
        public string ContainerSequenceNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ContainerSequenceNumbers {\n");
            sb.Append("  ContainerSequenceNumber: ").Append(ContainerSequenceNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as ContainerSequenceNumbers);
        }

        public bool Equals(ContainerSequenceNumbers input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ContainerSequenceNumber == input.ContainerSequenceNumber ||
                    (this.ContainerSequenceNumber != null &&
                    this.ContainerSequenceNumber.Equals(input.ContainerSequenceNumber))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ContainerSequenceNumber != null)
                    hashCode = hashCode * 59 + this.ContainerSequenceNumber.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}