/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to vendor shipment data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorShipments
{
    /// <summary>
    /// The request schema for the SubmitShipments operation.
    /// </summary>
    [DataContract]
    public partial class SubmitShipments :  IEquatable<SubmitShipments>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitShipments" /> class.
        /// </summary>
        [JsonConstructor]
        public SubmitShipments() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitShipments" /> class.
        /// </summary>
        /// <param name="shipments">A list of one or more shipments with underlying details.</param>
        public SubmitShipments(List<Shipment> shipments = default(List<Shipment>))
        {
            this.Shipments = shipments;
        }
        
        /// <summary>
        /// A list of one or more shipments with underlying details.
        /// </summary>
        /// <value>A list of one or more shipments with underlying details.</value>
        [DataMember(Name="shipments", EmitDefaultValue=false)]
        public List<Shipment> Shipments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubmitShipments {\n");
            sb.Append("  Shipments: ").Append(Shipments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as SubmitShipments);
        }

        public bool Equals(SubmitShipments input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Shipments == input.Shipments ||
                    (this.Shipments != null &&
                    this.Shipments.Equals(input.Shipments))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Shipments != null)
                    hashCode = hashCode * 59 + this.Shipments.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}