/* 
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * OpenAPI spec version: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.ExternalFulfillmentShipment
{
    /// <summary>
    /// A distance measurement.
    /// </summary>
    [DataContract]
    public partial class Distance :  IEquatable<Distance>, IValidatableObject
    {
        /// <summary>
        /// The unit of measurement of the distance.
        /// </summary>
        /// <value>The unit of measurement of the distance.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DistanceUnitEnum
        {
            
            /// <summary>
            /// Enum MI for value: MI
            /// </summary>
            [EnumMember(Value = "MI")]
            MI = 1,
            
            /// <summary>
            /// Enum KM for value: KM
            /// </summary>
            [EnumMember(Value = "KM")]
            KM = 2
        }

        /// <summary>
        /// The unit of measurement of the distance.
        /// </summary>
        /// <value>The unit of measurement of the distance.</value>
        [DataMember(Name="distanceUnit", EmitDefaultValue=false)]
        public DistanceUnitEnum DistanceUnit { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Distance" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Distance() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Distance" /> class.
        /// </summary>
        /// <param name="value">The numerical value of the distance. (required).</param>
        /// <param name="distanceUnit">The unit of measurement of the distance. (required).</param>
        public Distance(string value = default(string), DistanceUnitEnum distanceUnit = default(DistanceUnitEnum))
        {
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new InvalidDataException("value is a required property for Distance and cannot be null");
            }
            else
            {
                this.Value = value;
            }
            // to ensure "distanceUnit" is required (not null)
            if (distanceUnit == null)
            {
                throw new InvalidDataException("distanceUnit is a required property for Distance and cannot be null");
            }
            else
            {
                this.DistanceUnit = distanceUnit;
            }
        }
        
        /// <summary>
        /// The numerical value of the distance.
        /// </summary>
        /// <value>The numerical value of the distance.</value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Distance {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  DistanceUnit: ").Append(DistanceUnit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Distance);
        }

        /// <summary>
        /// Returns true if Distance instances are equal
        /// </summary>
        /// <param name="input">Instance of Distance to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Distance input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.DistanceUnit == input.DistanceUnit ||
                    (this.DistanceUnit != null &&
                    this.DistanceUnit.Equals(input.DistanceUnit))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                if (this.DistanceUnit != null)
                    hashCode = hashCode * 59 + this.DistanceUnit.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
