/* 
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * OpenAPI spec version: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.ExternalFulfillmentShipment
{
    /// <summary>
    /// The drop-off location details for package handover.
    /// </summary>
    [DataContract]
    public partial class HandoverLocation :  IEquatable<HandoverLocation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HandoverLocation" /> class.
        /// </summary>
        /// <param name="address">The address of the drop-off location..</param>
        /// <param name="distance">The distance from the seller&#39;s location to the drop-off point..</param>
        /// <param name="mapUrl">URL to the map that shows the drop-off location..</param>
        public HandoverLocation(Address address = default(Address), Distance distance = default(Distance), string mapUrl = default(string))
        {
            this.Address = address;
            this.Distance = distance;
            this.MapUrl = mapUrl;
        }
        
        /// <summary>
        /// The address of the drop-off location.
        /// </summary>
        /// <value>The address of the drop-off location.</value>
        [DataMember(Name="address", EmitDefaultValue=false)]
        public Address Address { get; set; }

        /// <summary>
        /// The distance from the seller&#39;s location to the drop-off point.
        /// </summary>
        /// <value>The distance from the seller&#39;s location to the drop-off point.</value>
        [DataMember(Name="distance", EmitDefaultValue=false)]
        public Distance Distance { get; set; }

        /// <summary>
        /// URL to the map that shows the drop-off location.
        /// </summary>
        /// <value>URL to the map that shows the drop-off location.</value>
        [DataMember(Name="mapUrl", EmitDefaultValue=false)]
        public string MapUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HandoverLocation {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("  MapUrl: ").Append(MapUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HandoverLocation);
        }

        /// <summary>
        /// Returns true if HandoverLocation instances are equal
        /// </summary>
        /// <param name="input">Instance of HandoverLocation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HandoverLocation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.Distance == input.Distance ||
                    (this.Distance != null &&
                    this.Distance.Equals(input.Distance))
                ) && 
                (
                    this.MapUrl == input.MapUrl ||
                    (this.MapUrl != null &&
                    this.MapUrl.Equals(input.MapUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Address != null)
                    hashCode = hashCode * 59 + this.Address.GetHashCode();
                if (this.Distance != null)
                    hashCode = hashCode * 59 + this.Distance.GetHashCode();
                if (this.MapUrl != null)
                    hashCode = hashCode * 59 + this.MapUrl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
