/* 
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * OpenAPI spec version: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.ExternalFulfillmentShipment
{
    /// <summary>
    /// Metadata for a ship label document.
    /// </summary>
    [DataContract]
    public partial class ShipLabelMetadata :  IEquatable<ShipLabelMetadata>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipLabelMetadata" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShipLabelMetadata() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipLabelMetadata" /> class.
        /// </summary>
        /// <param name="shippingOptionId">The selected slot for the ship label..</param>
        /// <param name="carrierName">The name of the carrier. (required).</param>
        /// <param name="trackingId">The tracking number of the package. (required).</param>
        /// <param name="pickupWindow">The time window during which the package was picked up..</param>
        /// <param name="timeSlot">A time window during which to hand over the package to Amazon Logistics..</param>
        /// <param name="handoverLocation">The drop-off location details. This value is populated when &#x60;handoverMethod&#x60; is &#x60;DROPOFF&#x60;..</param>
        public ShipLabelMetadata(string shippingOptionId = default(string), string carrierName = default(string), string trackingId = default(string), TimeWindow pickupWindow = default(TimeWindow), TimeWindow timeSlot = default(TimeWindow), HandoverLocation handoverLocation = default(HandoverLocation))
        {
            // to ensure "carrierName" is required (not null)
            if (carrierName == null)
            {
                throw new InvalidDataException("carrierName is a required property for ShipLabelMetadata and cannot be null");
            }
            else
            {
                this.CarrierName = carrierName;
            }
            // to ensure "trackingId" is required (not null)
            if (trackingId == null)
            {
                throw new InvalidDataException("trackingId is a required property for ShipLabelMetadata and cannot be null");
            }
            else
            {
                this.TrackingId = trackingId;
            }
            this.ShippingOptionId = shippingOptionId;
            this.PickupWindow = pickupWindow;
            this.TimeSlot = timeSlot;
            this.HandoverLocation = handoverLocation;
        }
        
        /// <summary>
        /// The selected slot for the ship label.
        /// </summary>
        /// <value>The selected slot for the ship label.</value>
        [DataMember(Name="shippingOptionId", EmitDefaultValue=false)]
        public string ShippingOptionId { get; set; }

        /// <summary>
        /// The name of the carrier.
        /// </summary>
        /// <value>The name of the carrier.</value>
        [DataMember(Name="carrierName", EmitDefaultValue=false)]
        public string CarrierName { get; set; }

        /// <summary>
        /// The tracking number of the package.
        /// </summary>
        /// <value>The tracking number of the package.</value>
        [DataMember(Name="trackingId", EmitDefaultValue=false)]
        public string TrackingId { get; set; }

        /// <summary>
        /// The time window during which the package was picked up.
        /// </summary>
        /// <value>The time window during which the package was picked up.</value>
        [DataMember(Name="pickupWindow", EmitDefaultValue=false)]
        public TimeWindow PickupWindow { get; set; }

        /// <summary>
        /// A time window during which to hand over the package to Amazon Logistics.
        /// </summary>
        /// <value>A time window during which to hand over the package to Amazon Logistics.</value>
        [DataMember(Name="timeSlot", EmitDefaultValue=false)]
        public TimeWindow TimeSlot { get; set; }

        /// <summary>
        /// The drop-off location details. This value is populated when &#x60;handoverMethod&#x60; is &#x60;DROPOFF&#x60;.
        /// </summary>
        /// <value>The drop-off location details. This value is populated when &#x60;handoverMethod&#x60; is &#x60;DROPOFF&#x60;.</value>
        [DataMember(Name="handoverLocation", EmitDefaultValue=false)]
        public HandoverLocation HandoverLocation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ShipLabelMetadata {\n");
            sb.Append("  ShippingOptionId: ").Append(ShippingOptionId).Append("\n");
            sb.Append("  CarrierName: ").Append(CarrierName).Append("\n");
            sb.Append("  TrackingId: ").Append(TrackingId).Append("\n");
            sb.Append("  PickupWindow: ").Append(PickupWindow).Append("\n");
            sb.Append("  TimeSlot: ").Append(TimeSlot).Append("\n");
            sb.Append("  HandoverLocation: ").Append(HandoverLocation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ShipLabelMetadata);
        }

        /// <summary>
        /// Returns true if ShipLabelMetadata instances are equal
        /// </summary>
        /// <param name="input">Instance of ShipLabelMetadata to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ShipLabelMetadata input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShippingOptionId == input.ShippingOptionId ||
                    (this.ShippingOptionId != null &&
                    this.ShippingOptionId.Equals(input.ShippingOptionId))
                ) && 
                (
                    this.CarrierName == input.CarrierName ||
                    (this.CarrierName != null &&
                    this.CarrierName.Equals(input.CarrierName))
                ) && 
                (
                    this.TrackingId == input.TrackingId ||
                    (this.TrackingId != null &&
                    this.TrackingId.Equals(input.TrackingId))
                ) && 
                (
                    this.PickupWindow == input.PickupWindow ||
                    (this.PickupWindow != null &&
                    this.PickupWindow.Equals(input.PickupWindow))
                ) && 
                (
                    this.TimeSlot == input.TimeSlot ||
                    (this.TimeSlot != null &&
                    this.TimeSlot.Equals(input.TimeSlot))
                ) && 
                (
                    this.HandoverLocation == input.HandoverLocation ||
                    (this.HandoverLocation != null &&
                    this.HandoverLocation.Equals(input.HandoverLocation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShippingOptionId != null)
                    hashCode = hashCode * 59 + this.ShippingOptionId.GetHashCode();
                if (this.CarrierName != null)
                    hashCode = hashCode * 59 + this.CarrierName.GetHashCode();
                if (this.TrackingId != null)
                    hashCode = hashCode * 59 + this.TrackingId.GetHashCode();
                if (this.PickupWindow != null)
                    hashCode = hashCode * 59 + this.PickupWindow.GetHashCode();
                if (this.TimeSlot != null)
                    hashCode = hashCode * 59 + this.TimeSlot.GetHashCode();
                if (this.HandoverLocation != null)
                    hashCode = hashCode * 59 + this.HandoverLocation.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
