/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorDirectFulfillmentShipping
{
    /// <summary>
    /// Represents a list of customer invoices, potentially paginated.
    /// </summary>
    [DataContract]
    public partial class CustomerInvoiceList :  IEquatable<CustomerInvoiceList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerInvoiceList" /> class.
        /// </summary>
        [JsonConstructor]
        public CustomerInvoiceList() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerInvoiceList" /> class.
        /// </summary>
        /// <param name="pagination">pagination.</param>
        /// <param name="customerInvoices">Represents a customer invoice within the CustomerInvoiceList.</param>
        public CustomerInvoiceList(Pagination pagination = default(Pagination), List<CustomerInvoice> customerInvoices = default(List<CustomerInvoice>))
        {
            this.Pagination = pagination;
            this.CustomerInvoices = customerInvoices;
        }
        
        /// <summary>
        /// Gets or Sets Pagination
        /// </summary>
        [DataMember(Name="pagination", EmitDefaultValue=false)]
        public Pagination Pagination { get; set; }

        /// <summary>
        /// Represents a customer invoice within the CustomerInvoiceList.
        /// </summary>
        /// <value>Represents a customer invoice within the CustomerInvoiceList.</value>
        [DataMember(Name="customerInvoices", EmitDefaultValue=false)]
        public List<CustomerInvoice> CustomerInvoices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CustomerInvoiceList {\n");
            sb.Append("  Pagination: ").Append(Pagination).Append("\n");
            sb.Append("  CustomerInvoices: ").Append(CustomerInvoices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as CustomerInvoiceList);
        }

        public bool Equals(CustomerInvoiceList input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Pagination == input.Pagination ||
                    (this.Pagination != null &&
                    this.Pagination.Equals(input.Pagination))
                ) && 
                (
                    this.CustomerInvoices == input.CustomerInvoices ||
                    (this.CustomerInvoices != null &&
                    this.CustomerInvoices.Equals(input.CustomerInvoices))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Pagination != null)
                    hashCode = hashCode * 59 + this.Pagination.GetHashCode();
                if (this.CustomerInvoices != null)
                    hashCode = hashCode * 59 + this.CustomerInvoices.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}