/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorDirectFulfillmentShipping
{
    /// <summary>
    /// Represents an item that has been packed into a container for shipping.
    /// </summary>
    [DataContract]
    public partial class PackedItem :  IEquatable<PackedItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PackedItem" /> class.
        /// </summary>
        [JsonConstructor]
        public PackedItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PackedItem" /> class.
        /// </summary>
        /// <param name="itemSequenceNumber">Item Sequence Number for the item. This must be the same value as sent in the order for a given item. (required)</param>
        /// <param name="buyerProductIdentifier">Buyer's Standard Identification Number (ASIN) of an item. Either buyerProductIdentifier or vendorProductIdentifier is required.</param>
        /// <param name="vendorProductIdentifier">The vendor selected product identification of the item. Should be the same as was sent in the Purchase Order, like SKU Number.</param>
        /// <param name="packedQuantity">Total item quantity packed in the container. (required)</param>
        public PackedItem(int? itemSequenceNumber = default(int?), string buyerProductIdentifier = default(string), string vendorProductIdentifier = default(string), ItemQuantity packedQuantity = default(ItemQuantity))
        {
            this.ItemSequenceNumber = itemSequenceNumber;
            this.BuyerProductIdentifier = buyerProductIdentifier;
            this.VendorProductIdentifier = vendorProductIdentifier;
            // to ensure "packedQuantity" is required (not null)
            if (packedQuantity == null)
            {
                throw new InvalidDataException("packedQuantity is a required property for PackedItem and cannot be null");
            }
            else
            {
                this.PackedQuantity = packedQuantity;
            }
        }
        
        /// <summary>
        /// Item Sequence Number for the item. This must be the same value as sent in the order for a given item.
        /// </summary>
        /// <value>Item Sequence Number for the item. This must be the same value as sent in the order for a given item.</value>
        [DataMember(Name="itemSequenceNumber", EmitDefaultValue=false)]
        public int? ItemSequenceNumber { get; set; }

        /// <summary>
        /// Buyer's Standard Identification Number (ASIN) of an item. Either buyerProductIdentifier or vendorProductIdentifier is required.
        /// </summary>
        /// <value>Buyer's Standard Identification Number (ASIN) of an item. Either buyerProductIdentifier or vendorProductIdentifier is required.</value>
        [DataMember(Name="buyerProductIdentifier", EmitDefaultValue=false)]
        public string BuyerProductIdentifier { get; set; }

        /// <summary>
        /// The vendor selected product identification of the item. Should be the same as was sent in the Purchase Order, like SKU Number.
        /// </summary>
        /// <value>The vendor selected product identification of the item. Should be the same as was sent in the Purchase Order, like SKU Number.</value>
        [DataMember(Name="vendorProductIdentifier", EmitDefaultValue=false)]
        public string VendorProductIdentifier { get; set; }

        /// <summary>
        /// Total item quantity packed in the container.
        /// </summary>
        /// <value>Total item quantity packed in the container.</value>
        [DataMember(Name="packedQuantity", EmitDefaultValue=false)]
        public ItemQuantity PackedQuantity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PackedItem {\n");
            sb.Append("  ItemSequenceNumber: ").Append(ItemSequenceNumber).Append("\n");
            sb.Append("  BuyerProductIdentifier: ").Append(BuyerProductIdentifier).Append("\n");
            sb.Append("  VendorProductIdentifier: ").Append(VendorProductIdentifier).Append("\n");
            sb.Append("  PackedQuantity: ").Append(PackedQuantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as PackedItem);
        }

        public bool Equals(PackedItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ItemSequenceNumber == input.ItemSequenceNumber ||
                    (this.ItemSequenceNumber != null &&
                    this.ItemSequenceNumber.Equals(input.ItemSequenceNumber))
                ) && 
                (
                    this.BuyerProductIdentifier == input.BuyerProductIdentifier ||
                    (this.BuyerProductIdentifier != null &&
                    this.BuyerProductIdentifier.Equals(input.BuyerProductIdentifier))
                ) && 
                (
                    this.VendorProductIdentifier == input.VendorProductIdentifier ||
                    (this.VendorProductIdentifier != null &&
                    this.VendorProductIdentifier.Equals(input.VendorProductIdentifier))
                ) && 
                (
                    this.PackedQuantity == input.PackedQuantity ||
                    (this.PackedQuantity != null &&
                    this.PackedQuantity.Equals(input.PackedQuantity))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ItemSequenceNumber != null)
                    hashCode = hashCode * 59 + this.ItemSequenceNumber.GetHashCode();
                if (this.BuyerProductIdentifier != null)
                    hashCode = hashCode * 59 + this.BuyerProductIdentifier.GetHashCode();
                if (this.VendorProductIdentifier != null)
                    hashCode = hashCode * 59 + this.VendorProductIdentifier.GetHashCode();
                if (this.PackedQuantity != null)
                    hashCode = hashCode * 59 + this.PackedQuantity.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}