/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorDirectFulfillmentShipping
{
    /// <summary>
    /// A list of packing slips.
    /// </summary>
    [DataContract]
    public partial class PackingSlipList :  IEquatable<PackingSlipList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PackingSlipList" /> class.
        /// </summary>
        [JsonConstructor]
        public PackingSlipList() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PackingSlipList" /> class.
        /// </summary>
        /// <param name="pagination">The pagination elements required to retrieve the remaining data.</param>
        /// <param name="packingSlips">An array of packing slip objects.</param>
        public PackingSlipList(Pagination pagination = default(Pagination), List<PackingSlip> packingSlips = default(List<PackingSlip>))
        {
            this.Pagination = pagination;
            this.PackingSlips = packingSlips;
        }
        
        /// <summary>
        /// The pagination elements required to retrieve the remaining data.
        /// </summary>
        /// <value>The pagination elements required to retrieve the remaining data.</value>
        [DataMember(Name="pagination", EmitDefaultValue=false)]
        public Pagination Pagination { get; set; }

        /// <summary>
        /// An array of packing slip objects.
        /// </summary>
        /// <value>An array of packing slip objects.</value>
        [DataMember(Name="packingSlips", EmitDefaultValue=false)]
        public List<PackingSlip> PackingSlips { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PackingSlipList {\n");
            sb.Append("  Pagination: ").Append(Pagination).Append("\n");
            sb.Append("  PackingSlips: ").Append(PackingSlips).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as PackingSlipList);
        }

        public bool Equals(PackingSlipList input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Pagination == input.Pagination ||
                    (this.Pagination != null &&
                    this.Pagination.Equals(input.Pagination))
                ) && 
                (
                    this.PackingSlips == input.PackingSlips ||
                    (this.PackingSlips != null &&
                    this.PackingSlips.Equals(input.PackingSlips))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Pagination != null)
                    hashCode = hashCode * 59 + this.Pagination.GetHashCode();
                if (this.PackingSlips != null)
                    hashCode = hashCode * 59 + this.PackingSlips.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}