/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorDirectFulfillmentShipping
{
    /// <summary>
    /// Response payload with the list of shipping labels
    /// </summary>
    [DataContract]
    public partial class ShippingLabelList :  IEquatable<ShippingLabelList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShippingLabelList" /> class.
        /// </summary>
        [JsonConstructor]
        public ShippingLabelList() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShippingLabelList" /> class.
        /// </summary>
        /// <param name="pagination">pagination.</param>
        /// <param name="shippingLabels">An array containing the details of the generated shipping labels.</param>
        public ShippingLabelList(Pagination pagination = default(Pagination), List<ShippingLabel> shippingLabels = default(List<ShippingLabel>))
        {
            this.Pagination = pagination;
            this.ShippingLabels = shippingLabels;
        }
        
        /// <summary>
        /// Gets or Sets Pagination
        /// </summary>
        [DataMember(Name="pagination", EmitDefaultValue=false)]
        public Pagination Pagination { get; set; }

        /// <summary>
        /// An array containing the details of the generated shipping labels.
        /// </summary>
        /// <value>An array containing the details of the generated shipping labels.</value>
        [DataMember(Name="shippingLabels", EmitDefaultValue=false)]
        public List<ShippingLabel> ShippingLabels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ShippingLabelList {\n");
            sb.Append("  Pagination: ").Append(Pagination).Append("\n");
            sb.Append("  ShippingLabels: ").Append(ShippingLabels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as ShippingLabelList);
        }

        public bool Equals(ShippingLabelList input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Pagination == input.Pagination ||
                    (this.Pagination != null &&
                    this.Pagination.Equals(input.Pagination))
                ) && 
                (
                    this.ShippingLabels == input.ShippingLabels ||
                    (this.ShippingLabels != null &&
                    this.ShippingLabels.Equals(input.ShippingLabels))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Pagination != null)
                    hashCode = hashCode * 59 + this.Pagination.GetHashCode();
                if (this.ShippingLabels != null)
                    hashCode = hashCode * 59 + this.ShippingLabels.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}