/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorDirectFulfillmentShipping
{
    /// <summary>
    /// Represents the request payload for submitting updates to the status of shipments, containing an array of one or more ShipmentStatusUpdate objects.
    /// </summary>
    [DataContract]
    public partial class SubmitShipmentStatusUpdatesRequest :  IEquatable<SubmitShipmentStatusUpdatesRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitShipmentStatusUpdatesRequest" /> class.
        /// </summary>
        [JsonConstructor]
        public SubmitShipmentStatusUpdatesRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitShipmentStatusUpdatesRequest" /> class.
        /// </summary>
        /// <param name="shipmentStatusUpdates">Contains a list of one or more ShipmentStatusUpdate objects, each representing an update to the status of a specific shipment.</param>
        public SubmitShipmentStatusUpdatesRequest(List<ShipmentStatusUpdate> shipmentStatusUpdates = default(List<ShipmentStatusUpdate>))
        {
            this.ShipmentStatusUpdates = shipmentStatusUpdates;
        }
        
        /// <summary>
        /// Contains a list of one or more ShipmentStatusUpdate objects, each representing an update to the status of a specific shipment.
        /// </summary>
        /// <value>Contains a list of one or more ShipmentStatusUpdate objects, each representing an update to the status of a specific shipment.</value>
        [DataMember(Name="shipmentStatusUpdates", EmitDefaultValue=false)]
        public List<ShipmentStatusUpdate> ShipmentStatusUpdates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubmitShipmentStatusUpdatesRequest {\n");
            sb.Append("  ShipmentStatusUpdates: ").Append(ShipmentStatusUpdates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as SubmitShipmentStatusUpdatesRequest);
        }

        public bool Equals(SubmitShipmentStatusUpdatesRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShipmentStatusUpdates == input.ShipmentStatusUpdates ||
                    (this.ShipmentStatusUpdates != null &&
                    this.ShipmentStatusUpdates.Equals(input.ShipmentStatusUpdates))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShipmentStatusUpdates != null)
                    hashCode = hashCode * 59 + this.ShipmentStatusUpdates.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}