/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorDirectFulfillmentShipping
{
    /// <summary>
    /// The request schema for the submitShipmentConfirmations operation.
    /// </summary>
    [DataContract]
    public partial class SubmitShipmentConfirmationsRequest :  IEquatable<SubmitShipmentConfirmationsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitShipmentConfirmationsRequest" /> class.
        /// </summary>
        [JsonConstructor]
        public SubmitShipmentConfirmationsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitShipmentConfirmationsRequest" /> class.
        /// </summary>
        /// <param name="shipmentConfirmations">Array of ShipmentConfirmation objects, each representing confirmation details for a specific shipment.</param>
        public SubmitShipmentConfirmationsRequest(List<ShipmentConfirmation> shipmentConfirmations = default(List<ShipmentConfirmation>))
        {
            this.ShipmentConfirmations = shipmentConfirmations;
        }
        
        /// <summary>
        /// Array of ShipmentConfirmation objects, each representing confirmation details for a specific shipment.
        /// </summary>
        /// <value>Array of ShipmentConfirmation objects, each representing confirmation details for a specific shipment.</value>
        [DataMember(Name="shipmentConfirmations", EmitDefaultValue=false)]
        public List<ShipmentConfirmation> ShipmentConfirmations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubmitShipmentConfirmationsRequest {\n");
            sb.Append("  ShipmentConfirmations: ").Append(ShipmentConfirmations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as SubmitShipmentConfirmationsRequest);
        }

        public bool Equals(SubmitShipmentConfirmationsRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShipmentConfirmations == input.ShipmentConfirmations ||
                    (this.ShipmentConfirmations != null &&
                    this.ShipmentConfirmations.Equals(input.ShipmentConfirmations))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShipmentConfirmations != null)
                    hashCode = hashCode * 59 + this.ShipmentConfirmations.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}