/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorDirectFulfillmentShipping
{
    /// <summary>
    /// The request schema for the submitShippingLabelRequest operation.
    /// </summary>
    [DataContract]
    public partial class SubmitShippingLabelsRequest :  IEquatable<SubmitShippingLabelsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitShippingLabelsRequest" /> class.
        /// </summary>
        [JsonConstructor]
        public SubmitShippingLabelsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitShippingLabelsRequest" /> class.
        /// </summary>
        /// <param name="shippingLabelRequests">An array of shipping label requests to be processed.</param>
        public SubmitShippingLabelsRequest(List<ShippingLabelRequest> shippingLabelRequests = default(List<ShippingLabelRequest>))
        {
            this.ShippingLabelRequests = shippingLabelRequests;
        }
        
        /// <summary>
        /// An array of shipping label requests to be processed.
        /// </summary>
        /// <value>An array of shipping label requests to be processed.</value>
        [DataMember(Name="shippingLabelRequests", EmitDefaultValue=false)]
        public List<ShippingLabelRequest> ShippingLabelRequests { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubmitShippingLabelsRequest {\n");
            sb.Append("  ShippingLabelRequests: ").Append(ShippingLabelRequests).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as SubmitShippingLabelsRequest);
        }

        public bool Equals(SubmitShippingLabelsRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShippingLabelRequests == input.ShippingLabelRequests ||
                    (this.ShippingLabelRequests != null &&
                    this.ShippingLabelRequests.Equals(input.ShippingLabelRequests))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShippingLabelRequests != null)
                    hashCode = hashCode * 59 + this.ShippingLabelRequests.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}