/*
 * Selling Partner API for Data Kiosk
 *
 * The Selling Partner API for Data Kiosk provides programmatic access to a seller's business data through GraphQL queries.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.DataKiosk
{
    /// <summary>
    /// Information required to create the query.
    /// </summary>
    [DataContract]
    public partial class CreateQuerySpecification :  IEquatable<CreateQuerySpecification>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateQuerySpecification" /> class.
        /// </summary>
        [JsonConstructor]
        public CreateQuerySpecification() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateQuerySpecification" /> class.
        /// </summary>
        /// <param name="query">The GraphQL query to submit. A query must be at most 8000 characters after unnecessary whitespace is removed. (required)</param>
        /// <param name="paginationToken">A token to fetch a certain page of query results when there are multiple pages of query results available. The value of this token must be fetched from the `pagination.nextToken` field of the `Query` object, and the `query` field for this object must also be set to the `query` field of the same `Query` object. A `Query` object can be retrieved from either the `getQueries` or `getQuery` operation. In the absence of this token value, the first page of query results will be requested.</param>
        public CreateQuerySpecification(string query = default(string), string paginationToken = default(string))
        {
            // to ensure "query" is required (not null)
            if (query == null)
            {
                throw new InvalidDataException("query is a required property for CreateQuerySpecification and cannot be null");
            }
            else
            {
                this.Query = query;
            }
            this.PaginationToken = paginationToken;
        }
        
        /// <summary>
        /// The GraphQL query to submit. A query must be at most 8000 characters after unnecessary whitespace is removed.
        /// </summary>
        /// <value>The GraphQL query to submit. A query must be at most 8000 characters after unnecessary whitespace is removed.</value>
        [DataMember(Name="query", EmitDefaultValue=false)]
        public string Query { get; set; }

        /// <summary>
        /// A token to fetch a certain page of query results when there are multiple pages of query results available. The value of this token must be fetched from the `pagination.nextToken` field of the `Query` object, and the `query` field for this object must also be set to the `query` field of the same `Query` object. A `Query` object can be retrieved from either the `getQueries` or `getQuery` operation. In the absence of this token value, the first page of query results will be requested.
        /// </summary>
        /// <value>A token to fetch a certain page of query results when there are multiple pages of query results available. The value of this token must be fetched from the `pagination.nextToken` field of the `Query` object, and the `query` field for this object must also be set to the `query` field of the same `Query` object. A `Query` object can be retrieved from either the `getQueries` or `getQuery` operation. In the absence of this token value, the first page of query results will be requested.</value>
        [DataMember(Name="paginationToken", EmitDefaultValue=false)]
        public string PaginationToken { get; set; }

        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateQuerySpecification {\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  PaginationToken: ").Append(PaginationToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as CreateQuerySpecification);
        }

        public bool Equals(CreateQuerySpecification input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Query == input.Query ||
                    (this.Query != null &&
                    this.Query.Equals(input.Query))
                ) && 
                (
                    this.PaginationToken == input.PaginationToken ||
                    (this.PaginationToken != null &&
                    this.PaginationToken.Equals(input.PaginationToken))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Query != null)
                    hashCode = hashCode * 59 + this.Query.GetHashCode();
                if (this.PaginationToken != null)
                    hashCode = hashCode * 59 + this.PaginationToken.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}