/*
 * Selling Partner API for Data Kiosk
 *
 * The Selling Partner API for Data Kiosk provides programmatic access to a seller's business data through GraphQL queries.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.DataKiosk
{
    /// <summary>
    /// The response for the `createQuery` operation.
    /// </summary>
    [DataContract]
    public partial class CreateQueryResponse :  IEquatable<CreateQueryResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateQueryResponse" /> class.
        /// </summary>
        [JsonConstructor]
        public CreateQueryResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateQueryResponse" /> class.
        /// </summary>
        /// <param name="queryId">The identifier for the query. This identifier is unique only in combination with a selling partner account ID. (required)</param>
        public CreateQueryResponse(string queryId = default(string))
        {
            // to ensure "queryId" is required (not null)
            if (queryId == null)
            {
                throw new InvalidDataException("queryId is a required property for CreateQueryResponse and cannot be null");
            }
            else
            {
                this.QueryId = queryId;
            }
        }
        
        /// <summary>
        /// The identifier for the query. This identifier is unique only in combination with a selling partner account ID.
        /// </summary>
        /// <value>The identifier for the query. This identifier is unique only in combination with a selling partner account ID.</value>
        [DataMember(Name="queryId", EmitDefaultValue=false)]
        public string QueryId { get; set; }

        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateQueryResponse {\n");
            sb.Append("  QueryId: ").Append(QueryId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as CreateQueryResponse);
        }

        public bool Equals(CreateQueryResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.QueryId == input.QueryId ||
                    (this.QueryId != null &&
                    this.QueryId.Equals(input.QueryId))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.QueryId != null)
                    hashCode = hashCode * 59 + this.QueryId.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}