/*
 * Selling Partner API for Data Kiosk
 *
 * The Selling Partner API for Data Kiosk provides programmatic access to a seller's business data through GraphQL queries.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.DataKiosk
{
    /// <summary>
    /// The response for the `getDocument` operation.
    /// </summary>
    [DataContract]
    public partial class GetDocumentResponse :  IEquatable<GetDocumentResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDocumentResponse" /> class.
        /// </summary>
        [JsonConstructor]
        public GetDocumentResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDocumentResponse" /> class.
        /// </summary>
        /// <param name="documentId">The identifier for the Data Kiosk document. This identifier is unique only in combination with a selling partner account ID. (required)</param>
        /// <param name="documentUrl">A presigned URL that can be used to retrieve the Data Kiosk document. This URL expires after 5 minutes. If the Data Kiosk document is compressed, the `Content-Encoding` header will indicate the compression algorithm.  **Note:** Most HTTP clients are capable of automatically decompressing downloaded files based on the `Content-Encoding` header. (required)</param>
        public GetDocumentResponse(string documentId = default(string), string documentUrl = default(string))
        {
            // to ensure "documentId" is required (not null)
            if (documentId == null)
            {
                throw new InvalidDataException("documentId is a required property for GetDocumentResponse and cannot be null");
            }
            else
            {
                this.DocumentId = documentId;
            }
            // to ensure "documentUrl" is required (not null)
            if (documentUrl == null)
            {
                throw new InvalidDataException("documentUrl is a required property for GetDocumentResponse and cannot be null");
            }
            else
            {
                this.DocumentUrl = documentUrl;
            }
        }
        
        /// <summary>
        /// The identifier for the Data Kiosk document. This identifier is unique only in combination with a selling partner account ID.
        /// </summary>
        /// <value>The identifier for the Data Kiosk document. This identifier is unique only in combination with a selling partner account ID.</value>
        [DataMember(Name="documentId", EmitDefaultValue=false)]
        public string DocumentId { get; set; }

        /// <summary>
        /// A presigned URL that can be used to retrieve the Data Kiosk document. This URL expires after 5 minutes. If the Data Kiosk document is compressed, the `Content-Encoding` header will indicate the compression algorithm.  **Note:** Most HTTP clients are capable of automatically decompressing downloaded files based on the `Content-Encoding` header.
        /// </summary>
        /// <value>A presigned URL that can be used to retrieve the Data Kiosk document. This URL expires after 5 minutes. If the Data Kiosk document is compressed, the `Content-Encoding` header will indicate the compression algorithm.  **Note:** Most HTTP clients are capable of automatically decompressing downloaded files based on the `Content-Encoding` header.</value>
        [DataMember(Name="documentUrl", EmitDefaultValue=false)]
        public string DocumentUrl { get; set; }

        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetDocumentResponse {\n");
            sb.Append("  DocumentId: ").Append(DocumentId).Append("\n");
            sb.Append("  DocumentUrl: ").Append(DocumentUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as GetDocumentResponse);
        }

        public bool Equals(GetDocumentResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DocumentId == input.DocumentId ||
                    (this.DocumentId != null &&
                    this.DocumentId.Equals(input.DocumentId))
                ) && 
                (
                    this.DocumentUrl == input.DocumentUrl ||
                    (this.DocumentUrl != null &&
                    this.DocumentUrl.Equals(input.DocumentUrl))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DocumentId != null)
                    hashCode = hashCode * 59 + this.DocumentId.GetHashCode();
                if (this.DocumentUrl != null)
                    hashCode = hashCode * 59 + this.DocumentUrl.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}