/*
 * Selling Partner API for Data Kiosk
 *
 * The Selling Partner API for Data Kiosk provides programmatic access to a seller's business data through GraphQL queries.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.DataKiosk
{
    /// <summary>
    /// The response for the `getQueries` operation.
    /// </summary>
    [DataContract]
    public partial class GetQueriesResponse :  IEquatable<GetQueriesResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetQueriesResponse" /> class.
        /// </summary>
        [JsonConstructor]
        public GetQueriesResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetQueriesResponse" /> class.
        /// </summary>
        /// <param name="queries">The Data Kiosk queries. (required)</param>
        /// <param name="pagination">When a request has results that are not included in this response, pagination occurs. This means the results are divided into pages. To retrieve the next page, you must pass the `nextToken` as the `paginationToken` query parameter in the subsequent `getQueries` request. All other parameters must be provided with the same values that were provided with the request that generated this token, with the exception of `pageSize` which can be modified between calls to `getQueries`. When there are no more pages to fetch, the `nextToken` field will be absent.</param>
        public GetQueriesResponse(QueryList queries = default(QueryList), Pagination pagination = default(Pagination))
        {
            // to ensure "queries" is required (not null)
            if (queries == null)
            {
                throw new InvalidDataException("queries is a required property for GetQueriesResponse and cannot be null");
            }
            else
            {
                this.Queries = queries;
            }
            this.Pagination = pagination;
        }
        
        /// <summary>
        /// The Data Kiosk queries.
        /// </summary>
        /// <value>The Data Kiosk queries.</value>
        [DataMember(Name="queries", EmitDefaultValue=false)]
        public QueryList Queries { get; set; }

        /// <summary>
        /// When a request has results that are not included in this response, pagination occurs. This means the results are divided into pages. To retrieve the next page, you must pass the `nextToken` as the `paginationToken` query parameter in the subsequent `getQueries` request. All other parameters must be provided with the same values that were provided with the request that generated this token, with the exception of `pageSize` which can be modified between calls to `getQueries`. When there are no more pages to fetch, the `nextToken` field will be absent.
        /// </summary>
        /// <value>When a request has results that are not included in this response, pagination occurs. This means the results are divided into pages. To retrieve the next page, you must pass the `nextToken` as the `paginationToken` query parameter in the subsequent `getQueries` request. All other parameters must be provided with the same values that were provided with the request that generated this token, with the exception of `pageSize` which can be modified between calls to `getQueries`. When there are no more pages to fetch, the `nextToken` field will be absent.</value>
        [DataMember(Name="pagination", EmitDefaultValue=false)]
        public Pagination Pagination { get; set; }

        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetQueriesResponse {\n");
            sb.Append("  Queries: ").Append(Queries).Append("\n");
            sb.Append("  Pagination: ").Append(Pagination).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as GetQueriesResponse);
        }

        public bool Equals(GetQueriesResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Queries == input.Queries ||
                    (this.Queries != null &&
                    this.Queries.Equals(input.Queries))
                ) && 
                (
                    this.Pagination == input.Pagination ||
                    (this.Pagination != null &&
                    this.Pagination.Equals(input.Pagination))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Queries != null)
                    hashCode = hashCode * 59 + this.Queries.GetHashCode();
                if (this.Pagination != null)
                    hashCode = hashCode * 59 + this.Pagination.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}