/*
 * Selling Partner API for Retail Procurement Payments
 *
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendor invoice data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorInvoices
{
    /// <summary>
    /// ErrorList : List<Error>
    /// </summary>
    [DataContract]
    public partial class ErrorList : List<Error>,  IEquatable<ErrorList>, IValidatableObject
    {
        [JsonConstructor]
        public ErrorList() : base()
        {
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ErrorList {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as ErrorList);
        }

        public bool Equals(ErrorList input)
        {
            if (input == null)
                return false;
            return base.Equals(input);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                int hashCode = base.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
