/*
 * Selling Partner API for Retail Procurement Payments
 *
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendor invoice data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorInvoices
{
    /// <summary>
    /// Tax registration details of the entity.
    /// </summary>
    [DataContract]
    public partial class TaxRegistrationDetails :  IEquatable<TaxRegistrationDetails>, IValidatableObject
    {
        /// <summary>
        /// The tax registration type for the entity.
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TaxRegistrationTypeEnum
        {
            /// <summary>
            /// Enum VAT for value: VAT
            /// </summary>
            [EnumMember(Value = "VAT")]
            VAT = 1,

            /// <summary>
            /// Enum GST for value: GST
            /// </summary>
            [EnumMember(Value = "GST")]
            GST = 2

        }

        /// <summary>
        /// The tax registration type for the entity.
        /// </summary>
        [DataMember(Name="taxRegistrationType", EmitDefaultValue=false)]
        public TaxRegistrationTypeEnum? TaxRegistrationType { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxRegistrationDetails" /> class.
        /// </summary>
        [JsonConstructor]
        public TaxRegistrationDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxRegistrationDetails" /> class.
        /// </summary>
        /// <param name="taxRegistrationType">The tax registration type for the entity. (required)</param>
        /// <param name="taxRegistrationNumber">The tax registration number for the entity. For example, VAT ID, Consumption Tax ID. (required)</param>
        public TaxRegistrationDetails(TaxRegistrationTypeEnum? taxRegistrationType = default(TaxRegistrationTypeEnum?), string taxRegistrationNumber = default(string))
        {
            // to ensure "taxRegistrationType" is required (not null)
            if (taxRegistrationType == null)
            {
                throw new InvalidDataException("taxRegistrationType is a required property for TaxRegistrationDetails and cannot be null");
            }
            else
            {
                this.TaxRegistrationType = taxRegistrationType;
            }
            // to ensure "taxRegistrationNumber" is required (not null)
            if (taxRegistrationNumber == null)
            {
                throw new InvalidDataException("taxRegistrationNumber is a required property for TaxRegistrationDetails and cannot be null");
            }
            else
            {
                this.TaxRegistrationNumber = taxRegistrationNumber;
            }
        }
        
        /// <summary>
        /// The tax registration number for the entity. For example, VAT ID, Consumption Tax ID.
        /// </summary>
        /// <value>The tax registration number for the entity. For example, VAT ID, Consumption Tax ID.</value>
        [DataMember(Name="taxRegistrationNumber", EmitDefaultValue=false)]
        public string TaxRegistrationNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaxRegistrationDetails {\n");
            sb.Append("  TaxRegistrationType: ").Append(TaxRegistrationType).Append("\n");
            sb.Append("  TaxRegistrationNumber: ").Append(TaxRegistrationNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as TaxRegistrationDetails);
        }

        public bool Equals(TaxRegistrationDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TaxRegistrationType == input.TaxRegistrationType ||
                    (this.TaxRegistrationType != null &&
                    this.TaxRegistrationType.Equals(input.TaxRegistrationType))
                ) && 
                (
                    this.TaxRegistrationNumber == input.TaxRegistrationNumber ||
                    (this.TaxRegistrationNumber != null &&
                    this.TaxRegistrationNumber.Equals(input.TaxRegistrationNumber))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TaxRegistrationType != null)
                    hashCode = hashCode * 59 + this.TaxRegistrationType.GetHashCode();
                if (this.TaxRegistrationNumber != null)
                    hashCode = hashCode * 59 + this.TaxRegistrationNumber.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}