/*
 * Selling Partner API for Retail Procurement Payments
 *
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendor invoice data.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.VendorInvoices
{
    /// <summary>
    /// Response containing the transaction ID.
    /// </summary>
    [DataContract]
    public partial class TransactionId :  IEquatable<TransactionId>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionId" /> class.
        /// </summary>
        [JsonConstructor]
        public TransactionId() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionId" /> class.
        /// </summary>
        /// <param name="transactionId">GUID to identify this transaction. This value can be used with the Transaction Status API to return the status of this transaction.</param>
        public TransactionId(string transactionId = default(string))
        {
            this._TransactionId = transactionId;
        }
        
        /// <summary>
        /// GUID to identify this transaction. This value can be used with the Transaction Status API to return the status of this transaction.
        /// </summary>
        /// <value>GUID to identify this transaction. This value can be used with the Transaction Status API to return the status of this transaction.</value>
        [DataMember(Name="transactionId", EmitDefaultValue=false)]
        public string _TransactionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionId {\n");
            sb.Append("  _TransactionId: ").Append(_TransactionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionId);
        }

        public bool Equals(TransactionId input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._TransactionId == input._TransactionId ||
                    (this._TransactionId != null &&
                    this._TransactionId.Equals(input._TransactionId))
                );
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._TransactionId != null)
                    hashCode = hashCode * 59 + this._TransactionId.GetHashCode();
                return hashCode;
            }
        }

        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}